### ISSUE TITLE
An empty stream should not throw an error

### ISSUE THREAD

**Issue by matt2xu** [mthom/prolog_parser#6]
This causes an error when hitting Ctrl+D in scryer-prolog with the error:

`caught: error(syntax_error(unexpected_end_of_file),read_term/2)`

I will fix this.

**Comment by triska** [comment]
When pressing Ctrl-d immediately after posting `?- read(X).`, then `X` should be unified with `end_of_file`. Is this what you will be working on? Thank you a lot!

**Comment by mthom** [comment]
Thank you, please do!

**Comment by matt2xu** [comment]
> When pressing Ctrl-d immediately after posting `?- read(X).`, then `X` should be unified with `end_of_file`. Is this what you will be working on? Thank you a lot!

It does not seem related: what you are talking about is the existing behavior in the current release of scryer-prolog, before I introduced the bug.

**Comment by triska** [comment]
Currently, I get:

<pre>
<b>?- read(X).</b>
<i>Ctrl-d</i>

caught: error(syntax_error(unexpected_end_of_file),read/1)
</pre>

Expected: `X = end_of_file`.
